### ISSUE TITLE
报错Cannot find module './config'

### ISSUE THREAD

**Issue by 188** [awesomes-cn/new-awesomes#13]
bash-3.2# sudo npm run dev

> new-awesomes@1.0.0 dev /data/work/source/new-awesomes-master
> HOST=0.0.0.0 PORT=3333 nuxt

module.js:549
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/work/source/new-awesomes-master/nuxt.config.js:1:78)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at exports.loadNuxtConfig.argv (/data/work/source/new-awesomes-master/node_modules/nuxt/bin/common/utils.js:18:15)
    at Object.<anonymous> (/data/work/source/new-awesomes-master/node_modules/nuxt/bin/nuxt-dev:63:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! new-awesomes@1.0.0 dev: `HOST=0.0.0.0 PORT=3333 nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the new-awesomes@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bimohxh** [comment]
需要在根目录下创建一个配置文件 config.json 内容格式为

```json
{
  "CDN": "资源的CDN地址",
  "API": "接口地址"
}
```

**Comment by 188** [comment]
加上后 npm run dev  打开 localhost:3333 报下面的错
![image](https://user-images.githubusercontent.com/3905303/48944245-e56fac00-ef60-11e8-92c1-64eeec2acecc.png)

**Comment by bimohxh** [comment]
API 地址不对吧

**Comment by 188** [comment]
API需要单独部署吗

**Comment by bimohxh** [comment]
是的，这是前后端分离的项目
